plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "CS173 Introduction to Computer Science"
description: 

baseurl                  : "/Ursinus-CS173" # the subpath of your site, e.g. "/blog"

# Analytics
analytics:
  provider               :  "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-24052857-1"
    
# Reading Files
include:
  - .htaccess
  - _pages
  - files