plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

# Analytics
analytics:
  provider               :  "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-24052857-1"
    
# Reading Files
include:
  - .htaccess
  - _pages
  - files